import { autoGeneratedHashKey, rangeKey, table, attribute } from '@aws/dynamodb-data-mapper-annotations';

@table('airline')
export class AirlineEntity {

    @autoGeneratedHashKey()
    id: string;

    @attribute()
    name: string;

    @attribute({})
    limitMinimum: number;

    @attribute()
    limitMaximum: number;

    @attribute()
    percent: number;

    @attribute()
    range: string;

    @attribute()
    rules: Array<Rules>;

    @attribute()
    urlPhoto: string;
}

class Rules {

    @attribute()
    begin: number;

    @attribute()
    end: number;

    @attribute()
    quotation: number;
}